id: P000611
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1157
  title: སྒྱུ་མ་ལམ་གྱི་རིམ་པའི་འགྲེལ་པ
  author: ''
  volumes:
    6306ba13acd24667b35ea727b70ea138:
      image_group_id: I1CZ1578
      title: ''
      volume_number: 1
      total_pages: 40
